# cloudbuild.yaml
steps:
  # Set a persistent volume according to /cloud-build/docs/build-config (search for volumes)
  - name: 'ubuntu'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: [ 'cp', '-a', '.', '/persistent_volume' ]

  # Build APK with Gradle Image from mounted /persistent_volume using name: vol1
  - name: 'gcr.io/cloud-builders/docker'
    volumes:
      - name: 'vol1'
        path: '/persistent_volume'
    args: [ 'run', '-v', 'vol1:/home/app', '--rm', 'gcr.io/fullstackgcp/gradle', '/bin/sh', '-c', 'cd /home/app && ./gradlew clean assembleRelease publish' ]
